---
- name: "Restart the host monitoring service"
  service:
    name: "{{ osohm_host_monitoring }}"
    state: restarted
  with_items: "{{ groups.nodes }}"
  loop_control:
    loop_var: host
  when: "{{ hostvars[host]['openshift_node_labels']['host-monitoring'] is defined }}"
  delegate_to: "{{ host }}"
  remote_user: "{{ ansible_ssh_user | default(omit) }}"  # Work around Ansible issue regarding copy, delegate_to and sudo
  become: "{{ ansible_become | default(omit) }}"

#  when: osohm_service_enabled | bool
